//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace elearning.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AlumnoLeccion
    {
        public int IdAlumnoLeccion { get; set; }
        public int IdAlumnoCurso { get; set; }
        public int IdLeccion { get; set; }
        public Nullable<decimal> Calificacion { get; set; }
    
        public virtual Leccion Leccion { get; set; }
        public virtual AlumnoCurso AlumnoCurso { get; set; }
    }
}
