//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace elearning.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AlumnoCurso
    {
        public int IdAlumnoCurso { get; set; }
        public int IdAlumno { get; set; }
        public int IdCurso { get; set; }
        public Nullable<int> IdMaestro { get; set; }
        public int IdAlumnoCursoEstatus { get; set; }
        public Nullable<decimal> Calificacion { get; set; }
    
        public virtual AlumnoCursoEstatus AlumnoCursoEstatus { get; set; }
        public virtual Curso Curso { get; set; }
        public virtual Usuario Usuario { get; set; }
        public virtual Usuario Usuario1 { get; set; }
    }
}
