//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace elearning.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Leccion
    {
        public int IdLeccion { get; set; }
        public string Leccion1 { get; set; }
        public string Descripcion { get; set; }
        public string Contenido { get; set; }
        public int IdCurso { get; set; }
        public decimal PuntajeAprobatorio { get; set; }
        public string Estatus { get; set; }
    
        public virtual Curso Curso { get; set; }
    }
}
