//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace elearning.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class elearningEntities : DbContext
    {
        public elearningEntities()
            : base("name=elearningEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AlumnoCursoEstatus> AlumnoCursoEstatus { get; set; }
        public virtual DbSet<AlumnoLeccion> AlumnoLeccion { get; set; }
        public virtual DbSet<AlumnoPregunta> AlumnoPregunta { get; set; }
        public virtual DbSet<Curso> Curso { get; set; }
        public virtual DbSet<TipoPregunta> TipoPregunta { get; set; }
        public virtual DbSet<Usuario> Usuario { get; set; }
        public virtual DbSet<Leccion> Leccion { get; set; }
        public virtual DbSet<Respuesta> Respuesta { get; set; }
        public virtual DbSet<Pregunta> Pregunta { get; set; }
        public virtual DbSet<AlumnoCurso> AlumnoCurso { get; set; }
    }
}
