//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace elearning.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pregunta
    {
        public int IdPregunta { get; set; }
        public string Pregunta1 { get; set; }
        public int IdTipoPregunta { get; set; }
        public int IdLeccion { get; set; }
        public Nullable<decimal> Puntos { get; set; }
        public string Estatus { get; set; }
    
        public virtual Leccion Leccion { get; set; }
        public virtual TipoPregunta TipoPregunta { get; set; }
    }
}
