//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace elearning.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Respuesta
    {
        public int IdRespuesta { get; set; }
        public string Respuesta1 { get; set; }
        public bool Correcta { get; set; }
        public int IdPregunta { get; set; }
        public string Estatus { get; set; }
    
        public virtual Pregunta Pregunta { get; set; }
    }
}
